using LiveDialogueTranslator.Core.Localization;
using LiveDialogueTranslator.Core.Startup;

namespace LiveDialogueTranslator.App.Services;

public sealed class Localizer
{
    private readonly ResolvedAppLanguage language;

    private Localizer(ResolvedAppLanguage language)
    {
        this.language = language;
    }

    public ResolvedAppLanguage Language => language;

    public static Localizer FromWindows()
    {
        return new Localizer(AppLanguageResolver.Resolve(AppLanguage.Auto));
    }

    public string Text(string key)
    {
        if (!Strings.TryGetValue(key, out var value))
        {
            return key;
        }

        return language == ResolvedAppLanguage.Korean ? value.Korean : value.English;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(Text(key), args);
    }

    private static readonly Dictionary<string, (string English, string Korean)> Strings = new(StringComparer.Ordinal)
    {
        ["AppTitle"] = ("LiveDialogue Translator", "LiveDialogue Translator"),
        ["StartCapture"] = ("Start capture", "캡처 시작"),
        ["StopCapture"] = ("Stop capture", "캡처 중지"),
        ["OverlayWindow"] = ("Overlay window", "오버레이 창"),
        ["AlwaysOnTop"] = ("Always on top", "항상 위"),
        ["Minimize"] = ("Minimize", "최소화"),
        ["Close"] = ("Close", "닫기"),
        ["Captions"] = ("Captions", "자막"),
        ["Settings"] = ("Settings", "설정"),
        ["Console"] = ("Console", "콘솔"),
        ["Info"] = ("Info", "정보"),
        ["Original"] = ("Original", "원문"),
        ["Translation"] = ("Translation", "번역"),
        ["Ready"] = ("Ready", "준비됨"),
        ["Stopped"] = ("Stopped", "중지됨"),
        ["Starting"] = ("Starting", "시작 중"),
        ["Listening"] = ("Listening", "듣는 중"),
        ["Restarting"] = ("Restarting", "다시 시작 중"),
        ["SettingsSaved"] = ("Settings saved", "설정 저장됨"),
        ["Warning"] = ("Warning", "경고"),
        ["Error"] = ("Error", "오류"),
        ["Fatal"] = ("Fatal", "치명적 오류"),
        ["Details"] = ("Details", "상세"),
        ["ActionNeeded"] = ("Action needed", "작업 필요"),
        ["Working"] = ("Working", "작업 중"),
        ["PressStart"] = ("Press start to capture system audio and microphone.", "시스템 오디오와 마이크를 캡처하려면 시작을 누르세요."),
        ["PreparingAudio"] = ("Preparing audio capture...", "오디오 캡처 준비 중..."),
        ["CheckingSetupTitle"] = ("Checking setup", "설정 확인 중"),
        ["PreparingEngine"] = ("Preparing local speech engine.", "로컬 음성 엔진 준비 중입니다."),
        ["SetupFailed"] = ("Setup failed", "설정 실패"),
        ["SetupUnavailable"] = ("Setup unavailable", "설정 사용 불가"),
        ["PythonUnavailable"] = ("Python setup is unavailable.", "Python 설정을 사용할 수 없습니다."),
        ["HfAccessNeeded"] = ("HF access needed", "HF 접근 필요"),
        ["LocalDiarizationSetup"] = ("Local diarization setup", "로컬 화자 식별 설정"),
        ["LocalDiarizationNeedsAccess"] = ("Local speaker diarization needs Hugging Face model access.", "로컬 화자 식별을 사용하려면 Hugging Face 모델 접근 권한이 필요합니다."),
        ["SetHfAccessCaption"] = ("Set Hugging Face access to enable local speaker diarization.", "로컬 화자 식별을 사용하려면 Hugging Face 접근 권한을 설정하세요."),
        ["WaitingForTranslation"] = ("Waiting for captions to translate.", "자막 번역을 기다리는 중입니다."),
        ["WaitingForSpeech"] = ("Waiting for speech...", "음성을 기다리는 중..."),
        ["LocalSttUnavailable"] = ("Local STT unavailable", "로컬 STT 사용 불가"),
        ["WorkerError"] = ("Worker error", "워커 오류"),
        ["SpeakerNamesSaved"] = ("Speaker names saved", "화자 이름 저장됨"),
        ["TranslationDetailsDefault"] = ("Translation and setup details will appear here.", "번역과 설정 상세 내용이 여기에 표시됩니다."),
        ["InstallWorkerTitle"] = ("Installing worker requirements", "워커 요구 사항 설치 중"),
        ["InstallWorkerCaption"] = ("Installing local STT packages and validating models.", "로컬 STT 패키지를 설치하고 모델을 검증 중입니다."),
        ["SetupReady"] = ("Setup ready", "설정 완료"),
        ["SetupReadyRestart"] = ("Worker requirements are ready. Restarting capture.", "워커 요구 사항이 준비되었습니다. 캡처를 다시 시작합니다."),
        ["SetupReadyStart"] = ("Worker requirements are ready. Press Start to capture audio.", "워커 요구 사항이 준비되었습니다. 오디오 캡처를 시작하려면 시작을 누르세요."),
        ["SetupFailedCaption"] = ("Setup failed.", "설정 실패."),
        ["Retry"] = ("Retry", "재시도"),
        ["RetryingDiarizationSetup"] = ("Retrying local diarization setup", "로컬 화자 식별 설정 재시도 중"),
        ["HfSavedRetrying"] = ("Saved Hugging Face access. Preparing local models again.", "Hugging Face 접근 권한을 저장했습니다. 로컬 모델을 다시 준비합니다."),
        ["HfAccessInstructions"] = ("Accept the Community-1 model terms, create a Hugging Face token, paste it here, then save. The app will retry automatically after that.", "Community-1 모델 약관에 동의하고 Hugging Face 토큰을 만든 뒤 여기에 붙여넣고 저장하세요. 저장 후 앱이 자동으로 다시 시도합니다."),
        ["HfAccessSaved"] = ("HF access saved", "HF 접근 저장됨"),
        ["HfAccessSavedDetail"] = ("Saved Hugging Face access. Local model setup will retry automatically when capture starts.", "Hugging Face 접근 권한을 저장했습니다. 캡처가 시작되면 로컬 모델 설정을 자동으로 다시 시도합니다."),
        ["Translating"] = ("Translating...", "번역 중..."),
        ["TranslationUnavailable"] = ("Translation unavailable: {0}", "번역 사용 불가: {0}"),
        ["TranslationRateLimited"] = ("Google is limiting translation requests. The next caption will try again after about {0} seconds. Add a Cloud Translation API key in Translation API settings for reliable live use.", "Google이 번역 요청을 제한하고 있습니다. 다음 자막은 약 {0}초 후 다시 시도합니다. 안정적인 실시간 사용을 위해 번역 API 설정에 Cloud Translation API 키를 추가하세요."),
        ["TranslateApi"] = ("Translate API", "번역 API"),
        ["ApiSetting"] = ("API Setting", "API 설정"),
        ["TranslationApiTitle"] = ("Google Translation API", "Google 번역 API"),
        ["TranslationApiDescription"] = ("For reliable live translation, enable Cloud Translation API and enter its API key. If the key is blank, the app uses a best-effort public endpoint that can be rate limited.", "안정적인 실시간 번역을 사용하려면 Cloud Translation API를 활성화하고 API 키를 입력하세요. 키가 비어 있으면 요청 제한이 발생할 수 있는 공개 경로를 보조적으로 사용합니다."),
        ["GoogleApiKey"] = ("Google API key", "Google API 키"),
        ["OpenGoogleCloud"] = ("Open Google Cloud", "Google Cloud 열기"),
        ["TranslationApiKeySaved"] = ("Translation API settings saved", "번역 API 설정 저장됨"),
        ["TranslationApiDummyHelp"] = ("Google supports an official Cloud Translation API key. Other translation APIs are planned integrations.", "Google은 공식 Cloud Translation API 키를 지원합니다. 다른 번역 API는 연동 예정입니다."),
        ["TranslationProviderAvailability"] = ("Google is available. Add an API key for reliable live translation; keyless mode can be rate limited.", "Google을 사용할 수 있습니다. 안정적인 실시간 번역에는 API 키를 추가하세요. 키 없이 사용할 때는 요청 제한이 발생할 수 있습니다."),
        ["TranslationProviderConfigured"] = ("Google Cloud Translation API key is configured.", "Google Cloud Translation API 키가 설정되었습니다."),
        ["TranslationProviderUnavailableItem"] = ("{0} (coming soon)", "{0} (준비 중)"),
        ["TranslationProviderUnavailable"] = ("This translation provider is not implemented yet.", "아직 구현되지 않은 번역 제공자입니다."),
        ["TranslationSupportInfo"] = ("Support status", "지원 상태"),
        ["TargetLanguage"] = ("Target Language", "번역 언어"),
        ["CaptionDisplayMode"] = ("Caption Display", "자막 표시"),
        ["DisplayOriginal"] = ("Original", "원문 보기"),
        ["DisplayTranslated"] = ("Translated", "번역본 보기"),
        ["DisplayBoth"] = ("Both", "동시에 보기"),
        ["SettingsAudioGroup"] = ("Audio Input", "오디오 입력"),
        ["SettingsAsrGroup"] = ("Speech Recognition", "음성 인식"),
        ["SettingsSpeakerProcessingGroup"] = ("Speaker Processing", "화자 처리"),
        ["SettingsTranslationGroup"] = ("Translation", "번역"),
        ["SettingsOverlayGroup"] = ("Captions and Overlay", "자막 및 오버레이"),
        ["SettingsToolsGroup"] = ("Management Tools", "관리 도구"),
        ["SettingsAudioDescription"] = ("Choose which Windows audio streams enter the pipeline.", "처리할 Windows 오디오 입력을 선택합니다."),
        ["SettingsAsrDescription"] = ("Convert speech into multilingual text. This does not separate speakers.", "음성을 다국어 텍스트로 변환합니다. 화자를 분리하는 단계는 아닙니다."),
        ["SettingsSpeakerDescription"] = ("Choose waveform separation for overlapping voices or timeline-based speaker identification.", "겹친 음성의 파형 분리와 시간대 기반 화자 식별을 설정합니다."),
        ["SettingsTranslationDescription"] = ("Translate recognized text into the selected target language.", "인식된 텍스트를 선택한 언어로 번역합니다."),
        ["SettingsOutputDescription"] = ("Control what captions show and how the overlay behaves.", "자막 표시 방식과 오버레이 동작을 조정합니다."),
        ["SettingsToolsDescription"] = ("Manage downloaded models and inspect Python runtime logs.", "다운로드한 모델을 관리하고 Python 실행 로그를 확인합니다."),
        ["AudioSources"] = ("Audio Sources", "오디오 소스"),
        ["SystemMic"] = ("System + Mic", "시스템 + 마이크"),
        ["SystemOnly"] = ("System Only", "시스템만"),
        ["MixedDevice"] = ("Mixed Device", "혼합 장치"),
        ["AudioInputSystemMicSummary"] = ("Captures Windows system audio and the default microphone as separate streams.", "Windows 시스템 음성과 기본 마이크를 별도 입력으로 캡처합니다."),
        ["AudioInputSystemOnlySummary"] = ("Captures Windows system audio only. The microphone is not opened.", "Windows 시스템 음성만 캡처하며 마이크는 사용하지 않습니다."),
        ["AudioInputMixedDeviceSummary"] = ("Captures the default input device as one mixed stream.", "기본 입력 장치를 하나의 혼합 스트림으로 캡처합니다."),
        ["AsrEngine"] = ("ASR Engine", "ASR 엔진"),
        ["FasterWhisper"] = ("Faster-Whisper", "Faster-Whisper"),
        ["QwenAsr"] = ("Qwen-ASR", "Qwen-ASR"),
        ["WhisperLiveKit"] = ("WhisperLiveKit", "WhisperLiveKit"),
        ["WhisperX"] = ("WhisperX", "WhisperX"),
        ["AsrEngineHint"] = ("The STT model list changes with the selected ASR engine: Faster-Whisper, Qwen3-ASR, WhisperLiveKit, or WhisperX.", "선택한 ASR 엔진에 따라 STT 모델 목록이 Faster-Whisper, Qwen3-ASR, WhisperLiveKit, WhisperX 기준으로 바뀝니다."),
        ["SttModel"] = ("STT Model", "STT 모델"),
        ["AsrModel"] = ("ASR Model", "ASR 모델"),
        ["SttLanguages"] = ("STT Languages", "STT 언어"),
        ["SttPreset"] = ("Preset", "프리셋"),
        ["Sensitive"] = ("Sensitive", "민감"),
        ["Balanced"] = ("Balanced", "균형"),
        ["Stable"] = ("Stable", "안정"),
        ["SttPresetWordOn"] = ("on", "켜짐"),
        ["SttPresetWordOff"] = ("off", "꺼짐"),
        ["SttPresetSummaryCommunity"] = ("{0}: STT chunk {1}s, beam {2}, word timestamps {3}, Community context {4}s", "{0}: STT 청크 {1}초, beam {2}, word timestamp {3}, Community 컨텍스트 {4}초"),
        ["SttPresetSummaryCommunityStable"] = ("{0}: STT chunk {1}s, beam {2}, diarized-turn ASR first, Community context {3}s", "{0}: STT 청크 {1}초, beam {2}, 화자 구간별 ASR 우선, Community 컨텍스트 {3}초"),
        ["SttPresetSummaryDiart"] = ("{0}: STT chunk {1}s, beam {2}, word timestamps {3}, Diart duration {4:0.#}s, step {5:0.#}s, latency {6:0.#}s", "{0}: STT 청크 {1}초, beam {2}, word timestamp {3}, Diart duration {4:0.#}초, step {5:0.#}초, latency {6:0.#}초"),
        ["SttPresetSummaryWhisperLiveKit"] = ("{0}: WhisperLiveKit uses selected Whisper model with Sortformer diarization internally. STT chunk {1}s, beam {2}.", "{0}: WhisperLiveKit은 선택한 Whisper 모델과 Sortformer 화자 식별을 내부에서 사용합니다. STT 청크 {1}초, beam {2}."),
        ["SttPresetSummaryWhisperX"] = ("{0}: WhisperX uses the selected Whisper model, chunk {1}s, beam {2}, alignment {3}.", "{0}: WhisperX는 선택한 Whisper 모델을 사용합니다. 청크 {1}초, beam {2}, alignment {3}."),
        ["SttPresetSummarySortformer"] = ("{0}: Sortformer diarization with ASR chunk {1}s, beam {2}.", "{0}: Sortformer 화자 식별, ASR 청크 {1}초, beam {2}."),
        ["SttPresetSummarySeparated"] = ("{0}: ASR chunk {1}s, beam {2}, after {3} separates overlapping voices.", "{0}: {3}가 겹친 음성을 분리한 뒤 ASR 청크 {1}초, beam {2}로 인식합니다."),
        ["SttLanguagesTitle"] = ("STT Languages", "STT 언어"),
        ["SttLanguageAuto"] = ("Auto", "자동"),
        ["SttLanguageMulti"] = ("{0} languages", "{0}개 언어"),
        ["SttLanguageHelp"] = ("Auto detects any language. Select one or more languages to restrict Whisper recognition.", "자동은 모든 언어를 감지합니다. Whisper 인식 언어를 제한하려면 하나 이상 선택하세요."),
        ["Compute"] = ("Compute", "연산 장치"),
        ["Auto"] = ("Auto", "자동"),
        ["SpeechSeparationSection"] = ("Overlapping Voice Separation", "겹친 음성 분리"),
        ["SpeechSeparationDescription"] = ("MossFormer2 or SepFormer splits two voices that speak at the same time into separate audio streams.", "MossFormer2 또는 SepFormer가 동시에 말하는 두 사람의 음성을 별도 음성으로 나눕니다."),
        ["SpeechSeparationModel"] = ("Separation Model", "분리 모델"),
        ["SpeechSeparationAuto"] = ("Auto recommendation", "자동 추천"),
        ["SpeechSeparationAutoWithModel"] = ("Auto: {0}", "자동: {0}"),
        ["SpeechSeparationOff"] = ("Off", "사용 안 함"),
        ["SpeechSeparationEffectiveAuto"] = ("Active model: {0} (automatic)", "적용 모델: {0} (자동 선택)"),
        ["SpeechSeparationEffectiveManual"] = ("Active model: {0}", "적용 모델: {0}"),
        ["SpeechSeparationEffectiveOff"] = ("Active model: Off", "적용 모델: 사용 안 함"),
        ["SpeechSeparationUnavailableItem"] = ("{0} (unavailable)", "{0} (사용 불가)"),
        ["SpeechSeparationRequirements"] = ("Requires {0:0.#} GB VRAM and {1:0.#} GB RAM with the current ASR.", "현재 ASR 조합에서 VRAM {0:0.#} GB와 RAM {1:0.#} GB가 필요합니다."),
        ["SpeechSeparationInsufficientVram"] = ("Available VRAM is {0:0.#} GB; {1:0.#} GB is required with the current ASR.", "현재 VRAM은 {0:0.#} GB이며 선택한 ASR 조합에는 {1:0.#} GB가 필요합니다."),
        ["SpeechSeparationInsufficientRam"] = ("Available RAM is {0:0.#} GB; {1:0.#} GB is required with the current ASR.", "현재 RAM은 {0:0.#} GB이며 선택한 ASR 조합에는 {1:0.#} GB가 필요합니다."),
        ["DetectHardwareAgain"] = ("Detect again", "하드웨어 다시 감지"),
        ["DetectingHardware"] = ("Detecting CPU, memory, and GPU...", "CPU, 메모리, GPU를 감지 중입니다..."),
        ["HardwareSummary"] = ("CPU: {0} ({1} threads), RAM: {2:0.#} GB, GPU: {3}", "CPU: {0} ({1}스레드), RAM: {2:0.#} GB, GPU: {3}"),
        ["HardwareGpuSummary"] = ("{0} ({1:0.#} GB VRAM)", "{0} (VRAM {1:0.#} GB)"),
        ["HardwareNoSupportedGpu"] = ("No supported NVIDIA GPU", "지원되는 NVIDIA GPU 없음"),
        ["SpeechSeparationRecommended"] = ("Recommended: {0}. {1}", "추천: {0}. {1}"),
        ["SpeechSeparationUnavailable"] = ("Speech separation disabled. {0}", "동시발화 분리를 사용할 수 없습니다. {0}"),
        ["SpeechSeparationReasonMoss"] = ("Best quality and 16 kHz integration fit for this hardware.", "이 하드웨어에서 품질과 16 kHz 통합 적합성이 가장 좋습니다."),
        ["SpeechSeparationReasonSepFormer"] = ("Fits the available VRAM with a stable 16 kHz checkpoint.", "현재 VRAM에 맞고 안정적인 16 kHz 체크포인트가 있습니다."),
        ["SpeechSeparationReasonCpu"] = ("CPU mode cannot meet the five-second target.", "CPU 모드에서는 5초 목표를 충족하기 어렵습니다."),
        ["SpeechSeparationReasonStreamingAsr"] = ("WhisperLiveKit cannot safely share one streaming session across two separated channels.", "WhisperLiveKit의 단일 스트리밍 세션은 분리된 두 채널을 안전하게 함께 처리할 수 없습니다."),
        ["SpeechSeparationReasonNoGpu"] = ("A CUDA-capable NVIDIA GPU is required for the five-second target.", "5초 목표에는 CUDA를 지원하는 NVIDIA GPU가 필요합니다."),
        ["SpeechSeparationReasonMemory"] = ("No supported model has enough GPU and system memory.", "GPU와 시스템 메모리를 만족하는 지원 모델이 없습니다."),
        ["SpeakerIdentificationSection"] = ("General Speaker Identification", "일반 화자 식별"),
        ["SpeakerIdentificationDescription"] = ("Community-1, Diart, or Sortformer labels who spoke when. It does not split overlapping waveforms.", "Community-1, Diart 또는 Sortformer가 시간대별 화자를 구분합니다. 겹친 음성 파형 자체를 나누지는 않습니다."),
        ["SpeakerIdentificationEnabled"] = ("Use general speaker identification", "일반 화자 식별 사용"),
        ["SpeakerIdentificationPaused"] = ("Paused while overlapping voice separation is active. The selected settings are preserved.", "겹친 음성 분리가 활성화되어 일시 중지됩니다. 선택한 설정은 그대로 보존됩니다."),
        ["SpeakerProcessingStatusSeparation"] = ("Active flow: {0} separates two overlapping voices, then ASR recognizes each stream.", "현재 처리: {0}가 겹친 두 음성을 분리한 뒤 ASR이 각 음성을 인식합니다."),
        ["SpeakerProcessingStatusIdentification"] = ("Active flow: {0} identifies speaker time ranges after ASR. Overlapping voices remain mixed.", "현재 처리: {0}가 ASR 결과의 화자 시간대를 식별합니다. 겹친 음성은 혼합된 상태로 남습니다."),
        ["SpeakerProcessingStatusOff"] = ("Active flow: ASR recognizes the mixed audio without speaker processing.", "현재 처리: 별도 화자 처리 없이 ASR이 혼합 음성을 인식합니다."),
        ["ModelManager"] = ("Model Manager", "모델 관리"),
        ["Open"] = ("Open", "열기"),
        ["Debug"] = ("Debug", "디버그"),
        ["OpenConsole"] = ("Open Python console", "Python 콘솔 열기"),
        ["Overlay"] = ("Overlay", "오버레이"),
        ["OverlayReset"] = ("Reset", "초기화"),
        ["OverlayResetTooltip"] = ("Reset overlay position, size, font, opacity, and border", "오버레이 위치, 크기, 글자 크기, 투명도, 테두리 초기화"),
        ["OverlayColors"] = ("Colors", "색상"),
        ["OverlayOpacity"] = ("Opacity", "투명도"),
        ["OverlayBorder"] = ("Border", "테두리"),
        ["ClickThroughHelp"] = ("Let mouse clicks pass through the overlay to the window behind it. Turn this off from Settings if the overlay cannot be clicked.", "마우스 클릭이 오버레이를 통과해 뒤의 창으로 전달됩니다. 오버레이를 클릭할 수 없으면 설정에서 이 옵션을 끄세요."),
        ["OverlayColorRole"] = ("Role", "항목"),
        ["OverlayColorValue"] = ("Color", "색상값"),
        ["OverlayColorPreview"] = ("Preview", "미리보기"),
        ["ActiveSpeakerColor"] = ("Active speaker", "활성 화자"),
        ["InactiveSpeakerColor"] = ("Inactive speaker", "비활성 화자"),
        ["ActiveOriginalColor"] = ("Active original", "활성 화자 원문"),
        ["ActiveTranslationColor"] = ("Active translation", "활성 화자 번역본"),
        ["InactiveOriginalColor"] = ("Inactive original", "비활성 화자 원문"),
        ["InactiveTranslationColor"] = ("Inactive translation", "비활성 화자 번역본"),
        ["ResetDefaults"] = ("Defaults", "기본값"),
        ["InvalidColor"] = ("Enter a valid color such as #FF8BD3FF.", "#FF8BD3FF 같은 올바른 색상값을 입력하세요."),
        ["PythonConsole"] = ("Python Console", "Python 콘솔"),
        ["ClearConsoleLogs"] = ("Clear logs", "로그 지우기"),
        ["KeepConsoleAtBottom"] = ("Keep bottom", "맨 밑 유지"),
        ["DebugState"] = ("Loaded: {0}   STT: {1}   Diarization: {2}   Speakers: {3}", "로드 모델: {0}   STT: {1}   화자 식별: {2}   화자: {3}"),
        ["ModelLine"] = ("Model: {0}", "모델: {0}"),
        ["LogLine"] = ("Log: {0}", "로그: {0}"),
        ["SpeakerExactDebug"] = ("exactly {0}", "정확히 {0}명"),
        ["SpeakerAutoDebug"] = ("auto / max {0}", "자동 / 최대 {0}"),
        ["ShowLatency"] = ("Show Latency", "지연시간 표시"),
        ["On"] = ("On", "켜기"),
        ["Speakers"] = ("Speakers", "화자"),
        ["AutoMax"] = ("Auto / max {0}", "자동 / 최대 {0}"),
        ["ExactSpeakers"] = ("Exactly {0}", "정확히 {0}명"),
        ["SpeakerMode"] = ("Speaker Mode", "화자 모드"),
        ["SpeakerModeActiveMax"] = ("Max active", "활성 최대"),
        ["SpeakerModeExact"] = ("Exact", "정확히"),
        ["SpeakerModeHelp"] = ("Exact keeps fixed speaker identities. Max active can replace inactive speakers when participants change.", "정확히는 화자 수를 고정합니다. 활성 최대는 참여자가 바뀌면 오래 안 나온 화자를 교체할 수 있습니다."),
        ["DisplayLines"] = ("Lines per speaker", "화자별 표시 줄 수"),
        ["CaptionDisplayLines"] = ("Caption page speaker lines", "자막 페이지 화자별 줄 수"),
        ["OverlayDisplayLines"] = ("Overlay caption lines", "오버레이 자막 줄 수"),
        ["Diarization"] = ("Speaker Identification", "화자 식별"),
        ["DiarizationModel"] = ("Identification Model", "화자 식별 모델"),
        ["DiarizationPreset"] = ("Identification Preset", "화자 식별 프리셋"),
        ["PyannoteCommunity"] = ("Community-1", "Community-1"),
        ["DiartRealtime"] = ("Diart Realtime", "Diart 실시간"),
        ["Sortformer"] = ("Sortformer", "Sortformer"),
        ["WhisperLiveKitSortformerManaged"] = ("WhisperLiveKit uses Sortformer internally. Community-1 and Diart settings are not used in this mode.", "WhisperLiveKit은 Sortformer를 내부에서 사용합니다. 이 모드에서는 Community-1과 Diart 설정을 사용하지 않습니다."),
        ["DiartManualTuning"] = ("Manual Diart tuning", "Diart 수동 조정"),
        ["DiartManualDescription"] = ("Manual values override the preset only for Diart. Good starting point: duration 5, step 0.5, latency 0.5/2/5 by preset, tau/rho/delta 0.555/0.422/1.517.", "수동값은 Diart에서만 프리셋을 덮어씁니다. 시작 권장값: duration 5, step 0.5, latency는 프리셋별 0.5/2/5, tau/rho/delta 0.555/0.422/1.517."),
        ["DiartDuration"] = ("Duration", "Duration"),
        ["DiartDurationHelp"] = ("Input audio window in seconds. 5 is the Diart default. Higher can stabilize speakers but may miss fast turns.", "입력 오디오 창 길이(초)입니다. Diart 기본값은 5입니다. 높이면 화자가 안정될 수 있지만 빠른 전환을 놓칠 수 있습니다."),
        ["DiartStep"] = ("Step", "Step"),
        ["DiartStepHelp"] = ("Update interval in seconds. 0.5 is the Diart default. Lower reacts faster but costs more CPU/GPU.", "업데이트 간격(초)입니다. Diart 기본값은 0.5입니다. 낮추면 빠르지만 CPU/GPU 사용량이 늘어납니다."),
        ["DiartLatency"] = ("Latency", "Latency"),
        ["DiartLatencyHelp"] = ("Algorithmic delay in seconds. Diart outputs audio time t-latency. Use 0.5-1 for realtime and 2-5 for steadier output.", "알고리즘 지연(초)입니다. Diart는 현재보다 latency만큼 과거 결과를 출력합니다. 실시간은 0.5~1, 안정성은 2~5를 사용합니다."),
        ["DiartTauActive"] = ("Tau", "Tau"),
        ["DiartTauActiveHelp"] = ("Speech activity threshold. Higher is stricter and may ignore quiet speech; lower accepts more speech/noise.", "발화 감지 임계값입니다. 높을수록 조용한 음성을 놓칠 수 있고, 낮을수록 음성/잡음을 더 많이 받아들입니다."),
        ["DiartRhoUpdate"] = ("Rho", "Rho"),
        ["DiartRhoUpdateHelp"] = ("Existing speaker profile update threshold. Higher is conservative; lower adapts faster but can drift.", "기존 화자 프로필 갱신 임계값입니다. 높으면 보수적이고, 낮으면 빨리 적응하지만 화자 정보가 흔들릴 수 있습니다."),
        ["DiartDeltaNew"] = ("Delta", "Delta"),
        ["DiartDeltaNewHelp"] = ("New speaker threshold. Lower creates new speakers more easily; higher resists speaker fragmentation.", "새 화자 생성 임계값입니다. 낮으면 새 화자가 쉽게 생기고, 높으면 화자 쪼개짐을 줄입니다."),
        ["SttPresetSummaryDiartManual"] = ("{0}: STT chunk {1}s, beam {2}, word timestamps {3}, Diart duration {4:0.##}s, step {5:0.##}s, latency {6:0.##}s", "{0}: STT 청크 {1}초, beam {2}, word timestamp {3}, Diart duration {4:0.##}초, step {5:0.##}초, latency {6:0.##}초"),
        ["SpeakerNames"] = ("Speaker Names", "화자 이름"),
        ["Rename"] = ("Rename", "이름 변경"),
        ["Install"] = ("Install", "설치"),
        ["SetAccess"] = ("Set Access", "접근 설정"),
        ["ModelManagerTitle"] = ("Model Manager", "모델 관리"),
        ["LocalModelSetup"] = ("Local model setup", "로컬 모델 설정"),
        ["ModelStoredDetail"] = ("Models are stored under LocalAppData. ASR runs with the selected Faster-Whisper, Qwen3-ASR, WhisperLiveKit, or WhisperX engine. Speaker diarization uses pyannote Community-1, Diart, or Sortformer. Two-speaker overlap separation uses MossFormer2 or SepFormer when the detected hardware supports it.", "모델은 LocalAppData에 저장됩니다. ASR은 선택한 Faster-Whisper, Qwen3-ASR, WhisperLiveKit, WhisperX 엔진으로 실행됩니다. 화자 식별은 pyannote Community-1, Diart, Sortformer를 사용하고, 2인 동시발화 분리는 감지된 하드웨어가 지원하는 경우 MossFormer2 또는 SepFormer를 사용합니다."),
        ["SupportedAsrBackends"] = ("ASR/STT", "ASR/STT"),
        ["SupportedDiarizationBackends"] = ("Diarization", "화자 식별"),
        ["SupportedSpeechSeparationBackends"] = ("Overlap separation", "동시발화 분리"),
        ["AccessNotice"] = ($"Accept the selected pyannote model terms, then create a token with this permission: {HuggingFaceLinks.TokenPermissionSummary}", $"선택한 pyannote 모델 약관에 동의한 뒤 다음 권한으로 토큰을 만드세요: {HuggingFaceLinks.TokenPermissionSummary}"),
        ["AccessNoticeExpanded"] = ($"Local diarization needs Hugging Face access before pyannote model files can be downloaded.{Environment.NewLine}{Environment.NewLine}1. Open Model Terms and accept access for the selected diarization model.{Environment.NewLine}2. Open Get Token and create a Fine-grained token.{Environment.NewLine}3. In User permissions > Repositories, enable: {HuggingFaceLinks.RequiredFineGrainedPermission}.{Environment.NewLine}4. Do not enable Write, Inference, Billing, Jobs, or Org permissions.{Environment.NewLine}5. Paste the token here and Save.", $"로컬 화자 식별 모델 파일을 다운로드하려면 Hugging Face 접근 권한이 필요합니다.{Environment.NewLine}{Environment.NewLine}1. Model Terms를 열고 선택한 화자 식별 모델의 접근 약관에 동의하세요.{Environment.NewLine}2. Get Token을 열고 Fine-grained 토큰을 만드세요.{Environment.NewLine}3. User permissions > Repositories에서 다음 항목만 켜세요: {HuggingFaceLinks.RequiredFineGrainedPermission}.{Environment.NewLine}4. Write, Inference, Billing, Jobs, Org 권한은 켜지 마세요.{Environment.NewLine}5. 토큰을 여기에 붙여넣고 저장하세요."),
        ["ModelDirectory"] = ("Model directory:{0}{1}", "모델 폴더:{0}{1}"),
        ["HfToken"] = ("HF Token", "HF 토큰"),
        ["GetToken"] = ("Get Token", "토큰 받기"),
        ["ModelTerms"] = ("Model Terms", "모델 약관"),
        ["CommunityTerms"] = ("Community-1", "Community-1"),
        ["DiartSegmentationTerms"] = ("Segmentation", "Segmentation"),
        ["DiartEmbeddingTerms"] = ("Embedding", "Embedding"),
        ["CheckAccess"] = ("Check", "접근 확인"),
        ["OpenFolder"] = ("Open Folder", "폴더 열기"),
        ["Prepare"] = ("Prepare", "준비"),
        ["Save"] = ("Save", "저장"),
        ["OpenTokenPage"] = ("Open Hugging Face access token page", "Hugging Face 토큰 발급 페이지 열기"),
        ["OpenCommunityModelPage"] = ("Open Community-1 model access page", "Community-1 모델 접근 페이지 열기"),
        ["OpenDiartSegmentationPage"] = ("Open pyannote/segmentation model access page", "pyannote/segmentation 모델 접근 페이지 열기"),
        ["OpenDiartEmbeddingPage"] = ("Open pyannote/embedding model access page", "pyannote/embedding 모델 접근 페이지 열기"),
        ["WorkerMissing"] = ("Worker script not found: {0}", "워커 스크립트를 찾을 수 없습니다: {0}"),
        ["UnableToStartPython"] = ("Unable to start Python.", "Python을 시작할 수 없습니다."),
        ["CheckingHfAccess"] = ("Checking Hugging Face model access", "Hugging Face 모델 접근 확인 중"),
        ["HfAccessNotRequired"] = ("Hugging Face pyannote access is not required for the selected ASR engine.", "선택한 ASR 엔진에는 Hugging Face pyannote 접근 권한이 필요하지 않습니다."),
        ["HfAccessOk"] = ("Hugging Face access verified. Model terms and token permission are valid.", "Hugging Face 접근이 확인되었습니다. 모델 약관 동의와 토큰 권한이 유효합니다."),
        ["HfAccessFailed"] = ("Hugging Face access check failed. Accept the model terms and verify token permissions.", "Hugging Face 접근 확인에 실패했습니다. 모델 약관 동의와 토큰 권한을 확인하세요."),
        ["SaveTokenBeforeCheck"] = ("Paste a Hugging Face token before checking access.", "접근 확인 전에 Hugging Face 토큰을 붙여넣으세요."),
        ["CheckingLocalSpeechSetup"] = ("Checking local speech setup", "로컬 음성 설정 확인 중"),
        ["CheckingPythonPackagesModels"] = ("Checking Python, packages, and model cache.", "Python, 패키지, 모델 캐시를 확인 중입니다."),
        ["PreparingPythonRuntime"] = ("Preparing app Python runtime", "앱 Python 런타임 준비 중"),
        ["CreatingAppPythonEnvironment"] = ("Preparing an app-managed Python runtime under LocalAppData.", "LocalAppData 아래에 앱 전용 Python 런타임을 준비 중입니다."),
        ["DownloadingPythonRuntime"] = ("Downloading Python runtime", "Python 런타임 다운로드 중"),
        ["DownloadingPythonRuntimeDetail"] = ("Downloading Python {0} from python.org.", "python.org에서 Python {0}을 다운로드 중입니다."),
        ["ExtractingPythonRuntime"] = ("Extracting Python runtime", "Python 런타임 압축 해제 중"),
        ["InstallingPythonRuntimeDetail"] = ("Preparing {0}", "{0} 준비 중입니다."),
        ["InstallingPip"] = ("Installing pip", "pip 설치 중"),
        ["DownloadingPipBootstrap"] = ("Downloading pip bootstrap.", "pip 부트스트랩을 다운로드 중입니다."),
        ["InstallingPipBootstrap"] = ("Installing pip into the app Python runtime.", "앱 Python 런타임에 pip를 설치 중입니다."),
        ["PythonRuntimeDownloadFailed"] = ("Python runtime download failed. Check the internet connection and retry.", "Python 런타임 다운로드에 실패했습니다. 인터넷 연결을 확인한 뒤 다시 시도하세요."),
        ["PythonRuntimeCreateFailed"] = ("Unable to create the app-managed Python runtime. Check antivirus or folder permissions, then retry.", "앱 전용 Python 런타임을 만들 수 없습니다. 백신 또는 폴더 권한을 확인한 뒤 다시 시도하세요."),
        ["PipBootstrapFailed"] = ("pip bootstrap failed in the app Python runtime.", "앱 Python 런타임에서 pip 부트스트랩에 실패했습니다."),
        ["UpgradingPip"] = ("Upgrading pip in the app Python environment.", "앱 Python 환경의 pip를 업데이트 중입니다."),
        ["PipUpgradeFailed"] = ("pip upgrade failed in the app Python environment.", "앱 Python 환경에서 pip 업데이트에 실패했습니다."),
        ["SpeechSetupWarning"] = ("Speech setup warning", "음성 설정 경고"),
        ["SpeechSetupReady"] = ("Speech setup ready", "음성 설정 완료"),
        ["InstallingLocalSpeechPackages"] = ("Installing local speech packages", "로컬 음성 패키지 설치 중"),
        ["ReinstallingWorkerRequirements"] = ("Reinstalling worker requirements.", "워커 요구 사항을 다시 설치 중입니다."),
        ["PreparingLocalSpeechModels"] = ("Preparing local speech models", "로컬 음성 모델 준비 중"),
        ["DownloadingOrValidatingModels"] = ("Downloading or validating model files.", "모델 파일을 다운로드하거나 검증 중입니다."),
        ["WorkerRequirementsReady"] = ("Worker requirements and STT model are ready.", "워커 요구 사항과 STT 모델이 준비되었습니다."),
        ["WorkerMissingTitle"] = ("Worker missing", "워커 없음"),
        ["CheckingPythonWorker"] = ("Checking Python worker", "Python 워커 확인 중"),
        ["PythonCheckFailed"] = ("Python check failed", "Python 확인 실패"),
        ["FirstInstallCanTakeMinutes"] = ("This can take several minutes on the first run.", "첫 실행에서는 몇 분 정도 걸릴 수 있습니다."),
        ["InstallingPackages"] = ("Installing packages", "패키지 설치 중"),
        ["InstallingDiartPackage"] = ("Installing the optional Diart runtime package.", "선택한 Diart 런타임 패키지를 설치 중입니다."),
        ["InstallingAsrEnginePackages"] = ("Installing ASR engine packages", "ASR 엔진 패키지 설치 중"),
        ["AsrEnginePackagesCanTakeMinutes"] = ("Installing the selected ASR engine into an isolated package directory. This can take several minutes and use a lot of disk space.", "선택한 ASR 엔진을 분리된 패키지 폴더에 설치 중입니다. 몇 분 정도 걸릴 수 있고 디스크 용량을 많이 사용할 수 있습니다."),
        ["InstallingSpeechSeparationPackages"] = ("Installing speech separation packages", "동시발화 분리 패키지 설치 중"),
        ["SpeechSeparationPackagesCanTakeMinutes"] = ("Installing the selected separation backend and its compatible runtime. The first setup can take several minutes.", "선택한 분리 백엔드와 호환 런타임을 설치 중입니다. 최초 설정에는 몇 분이 걸릴 수 있습니다."),
        ["PythonPackageInstallFailed"] = ("Python package installation failed.", "Python 패키지 설치 실패."),
        ["CheckingGpuAcceleration"] = ("Checking GPU acceleration", "GPU 가속 확인 중"),
        ["InstallingCudaAcceleration"] = ("Installing CUDA acceleration", "CUDA 가속 설치 중"),
        ["CudaInstallCanTakeMinutes"] = ("Installing CUDA-enabled PyTorch for the NVIDIA GPU. This can take several minutes.", "NVIDIA GPU용 CUDA PyTorch를 설치 중입니다. 몇 분 정도 걸릴 수 있습니다."),
        ["CudaAccelerationReady"] = ("CUDA acceleration is ready.", "CUDA 가속이 준비되었습니다."),
        ["CudaAccelerationInstallFailed"] = ("CUDA acceleration package installation failed.", "CUDA 가속 패키지 설치 실패."),
        ["PreparingModels"] = ("Preparing models", "모델 준비 중"),
        ["ModelPreparationFailed"] = ("Model preparation failed.", "모델 준비 실패."),
        ["SttDiarizationReady"] = ("STT and speaker diarization are ready.", "STT와 화자 식별이 준비되었습니다."),
        ["SttOnlyReady"] = ("STT is ready. Speaker diarization is disabled.", "STT가 준비되었습니다. 화자 식별은 꺼져 있습니다."),
        ["SpeechSeparationReady"] = ("STT and two-speaker overlap separation are ready.", "STT와 2인 동시발화 분리가 준비되었습니다."),
        ["LocalSpeechUnavailable"] = ("Local speech setup is unavailable.", "로컬 음성 설정을 사용할 수 없습니다."),
        ["SpeakerNamesTitle"] = ("Speaker Names", "화자 이름"),
        ["SpeakerRenameHelp"] = ("Rename automatically detected speakers.", "자동 감지된 화자 이름을 변경합니다."),
        ["Cancel"] = ("Cancel", "취소"),
        ["FontIncrease"] = ("Font size increase", "글자 크기 키우기"),
        ["FontDecrease"] = ("Font size decrease", "글자 크기 줄이기"),
        ["ClickThrough"] = ("Click through", "클릭 통과"),
        ["Lock"] = ("Lock", "잠금"),
        ["InfoWelcome"] = ("LiveDialogue Translator captures system audio and microphone input directly, prepares an app-managed Python runtime, then runs local STT and speaker processing before displaying translated captions in the main window or overlay.", "LiveDialogue Translator는 시스템 오디오와 마이크 입력을 직접 캡처하고 앱 전용 Python 런타임을 준비한 뒤 로컬 STT와 화자 처리를 실행해 번역 자막을 메인 창 또는 오버레이에 표시합니다."),
        ["InfoLinks"] = ("Credits and license", "크레딧 및 라이선스"),
        ["Project"] = ("Project", "프로젝트"),
        ["ReferenceProject"] = ("Reference", "레퍼런스"),
        ["Models"] = ("Models", "모델"),
        ["Runtime"] = ("Runtime", "런타임"),
        ["Data"] = ("Data", "데이터"),
        ["License"] = ("License", "라이선스"),
        ["Version"] = ("Version", "버전"),
        ["AppStorage"] = ("App storage", "앱 저장소"),
        ["PythonRuntime"] = ("Python runtime", "Python 런타임"),
        ["OpenModelsFolder"] = ("Open models folder", "모델 폴더 열기"),
        ["OpenRuntimeFolder"] = ("Open runtime folder", "런타임 폴더 열기"),
        ["PrivacyNote"] = ("Audio stays on this PC for STT and speaker processing. Hugging Face is used only for gated model downloads after token setup; translations are sent to the selected provider.", "오디오는 STT와 화자 처리 과정에서 이 PC 안에서 처리됩니다. Hugging Face는 토큰 설정 후 gated 모델 다운로드에만 사용되며, 번역 요청은 선택한 제공자로 전송됩니다.")
    };
}
